# Generated by Django 3.2.13 on 2022-06-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(verbose_name='atalho')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('image', models.ImageField(upload_to='courses/images', verbose_name='imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
        ),
    ]
